language: c
compiler: gcc
sudo: false
dist: trusty


install:
  - openssl aes-256-cbc -K $OPENSSL_KEY -iv $OPENSSL_IV -in just-containers/keys.tar.xz.enc -out just-containers/keys.tar.xz -d
  - tar xf just-containers/keys.tar.xz -C just-containers
  - gpg --import just-containers/keys/public.key
  - gpg --allow-secret-key-import --import just-containers/keys/private.key

script:
  - bash build

after_success:
  - bash upload
