language: c
compiler: gcc
sudo: required
dist: trusty


install:
  - openssl aes-256-cbc -K $OPENSSL_KEY -iv $OPENSSL_IV -in keys.tar.xz.enc -out keys.tar.xz -d
  - tar xf keys.tar.xz
  - gpg --import keys/public.key
  - gpg --allow-secret-key-import --import keys/private.key

script:
  - bash build

after_success:
  - bash upload
